# Site settings
title: Edgar Valle
email: edgvalle003@gmail.com
description: > # keep this and put description below
  Software and Gameplay Engineer
url: "https://edgvalle.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/edgar-v-95e23/"
github_username: EdgValle
twitter_username: devthedel
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
